# deployment:
#  hub:
#    branch: master
#    commands:
#      - $DEPLOY

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "web/requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r web/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "web/requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest discover web

      - store_artifacts:
          path: test-reports
          destination: test-reports
